In [1]:
import os
import requests
import pandas as pd
import time
import sqlalchemy
from dotenv import dotenv_values

In [2]:
weather_stations= ["KBFI0","72494","72295","72278","72365","KIWS0","72356","72334","72223","72211",
                   "72202","72327","72219","72314","72785","72681","72775","KP600","72572","KMIB0",
                   "72662","71850","72658","KYIP0","72405","CYMX0","72534","72421","72434","72446",
                   "72562","KBKF0","72476","KCDC0","72218","KCSG0","71954","70219","70030","70194", 
                   "70261","70362","70340","70273","KJXN0","KLRF0","72509","72518","72519","72519",
                   "72528","KFLO0","74756","72302","KNTU0","72306","72315","72258","72253","72248", 
                   "72783", "KBKE0", "KRDM0", "72694", "KLMT0", "72290", "72384", "72389", "72488", 
                   "KMCC0", "72594", "72214", "72207"]

weather_stations_dict={"KBFI0":"Seattle / South Park",
                       "72494":"San Francisco Airport",
                       "72295":"Los Angeles Airport",
                       "72278":"Phoenix Sky Harbor Airport",
                       "72365":"Albuquerque International  Airport",
                       "KIWS0":"Houston / Wood Fern",
                       "72356":"Tulsa International Airport",
                       "72334":"Memphis International Airport",
                       "72223":"Mobile Regional Airport",
                       "72211":"Tampa International Airport",
                       "72202":"Miami International Airport",
                       "72327":"Nashville Airport", 
                       "72219":"Hartsfield-Jackson Atlanta",
                       "72314":"Charlotte/Douglas International Airport",
                       "72785":"Spokane International Airport",
                       "72681":"Boise Air Terminal",
                       "72775":"Great Falls International",
                       "KP600":"Yellowstone / Lake",
                       "72572":"Salt Lake City International  Airport",
                       "KMIB0":"Minot / Minot Air Force Base",
                       "72662":"Rapid City Regional Airport", 
                       "71850":"Kenora Airport", 
                       "72658":"Minneapolis-St Paul International",
                       "KYIP0":"Detroit / Denton",
                       "72405":"Washington National Airport", 
                       "CYMX0":"Montreal / Mirabel",
                       "72534":"Chicago Midway Airport",
                       "72421":"Cincinnati/Northern Ky International",
                       "72434":"Lambert-St Louis International  Airport",
                       "72446":"Kansas City International Airport",
                       "72562":"North Platte Regional Airport",
                       "KBKF0":"Denver / Aurora / Side Creek",
                       "72476":"Grand Junction Walker Field",
                       "KCDC0":"Cedar City",
                       "72218":"Augusta Bush Field",
                       "KCSG0":"Columbus / Wayne Terrace",
                       "71954":"Tuktoyaktuk",
                       "70219":"Bethel Airport",
                       "70030":"Wainwright Airport",
                       "70194":"Fort Yukon Airport",
                       "70261":"Fairbanks Airport",
                       "70362":"Skagway Airport",
                       "70340":"Iliamna Airport",
                       "70273":"Anchorage Ted Stevens Airport",
                       "KJXN0":"Jackson / Coffman Trailer Court",
                       "KLRF0":"Little Rock / Jacksonville / Macon",
                       "72509":"Boston Logan International",
                       "72518":"Albany International Airport",
                       "72519":"Syracuse Hancock International  Airport",
                       "72528":"Buffalo Airport",
                       "KFLO0":"Florence / Malibu",
                       "74756":"Gainesville / Brittany Estates Mobile Home Park",
                       "72302":"Wilmington / The Palms Mobile Home Park",
                       "KNTU0":"Virginia Beach / Gatewood Park",
                       "72306":"Raleigh-Durham International  Airport",
                       "72315":"Asheville Regional Airport",
                       "72258":"Dallas / Oldham",
                       "72253":"San Antonio International  Airport",
                       "72248":"Shreveport Regional Airport",
                       "72783":"Lewiston Nez Perce Co Airport",
                       "KBKE0":"Baker / Estes (Historical)",
                       "KRDM0":"Redmond",
                       "72694":"Salem McNary Field",
                       "KLMT0":"Klamath Falls / Falcon Heights",
                       "72290":"San Diego International Airport",
                       "72384":"Bakersfield Meadows Field",
                       "72389":"Fresno Air Terminal",
                       "72488":"Reno/Tahoe International  Airport",
                       "KMCC0":"Sacramento / McClellan Park",
                       "72594":"Eureka",
                       "72214":"Tallahassee Airport",
                       "72207":"Savannah Airport"
                       }

In [4]:

# Load environment variables from the .env file
env_vars = dotenv_values(".env")

# Access the credentials using the loaded environment variables
api_key = env_vars["X-RapidAPI-Key"]
api_host = env_vars["X-RapidAPI-Host"]

# Use the credentials in your code
url = "https://meteostat.p.rapidapi.com/stations/daily"
weather_data_all = []

for station in weather_stations:
    querystring = {"station": station, "start": "1996-01-01", "end": "2005-01-01"}
    print(f'This is the weather for {station}')
    headers = {
        "X-RapidAPI-Key": api_key,  # Use the loaded API key
        "X-RapidAPI-Host": api_host  # Use the loaded API host
    }

    response = requests.get(url, headers=headers, params=querystring)
    weather_data_all.append(response.json())
    time.sleep(3)

This is the weather for KBFI0
This is the weather for 72494
This is the weather for 72295
This is the weather for 72278
This is the weather for 72365
This is the weather for KIWS0
This is the weather for 72356
This is the weather for 72334
This is the weather for 72223
This is the weather for 72211
This is the weather for 72202
This is the weather for 72327
This is the weather for 72219
This is the weather for 72314
This is the weather for 72785
This is the weather for 72681
This is the weather for 72775
This is the weather for KP600
This is the weather for 72572
This is the weather for KMIB0
This is the weather for 72662
This is the weather for 71850
This is the weather for 72658
This is the weather for KYIP0
This is the weather for 72405
This is the weather for CYMX0
This is the weather for 72534
This is the weather for 72421
This is the weather for 72434
This is the weather for 72446
This is the weather for 72562
This is the weather for KBKF0
This is the weather for 72476
This is the weather for KCDC0
This is the weather for 72218
This is the weather for KCSG0
This is the weather for 71954
This is the weather for 70219
This is the weather for 70030
This is the weather for 70194
This is the weather for 70261
This is the weather for 70362
This is the weather for 70340
This is the weather for 70273
This is the weather for KJXN0
This is the weather for KLRF0
This is the weather for 72509
This is the weather for 72518
This is the weather for 72519
This is the weather for 72519
This is the weather for 72528
This is the weather for KFLO0
This is the weather for 74756
This is the weather for 72302
This is the weather for KNTU0
This is the weather for 72306
This is the weather for 72315
This is the weather for 72258
This is the weather for 72253
This is the weather for 72248
This is the weather for 72783
This is the weather for KBKE0
This is the weather for KRDM0
This is the weather for 72694
This is the weather for KLMT0
This is the weather for 72290
This is the weather for 72384
This is the weather for 72389
This is the weather for 72488
This is the weather for KMCC0
This is the weather for 72594
This is the weather for 72214
This is the weather for 72207

In [5]:
weather_capstone = weather_data_all     
weather_df_capstone = pd.DataFrame([])
for station, json_element in zip(weather_stations,weather_capstone): #zipping weather_stations & weather_katrina
    weather_norm = pd.json_normalize(json_element, sep="_",
                                    record_path="data",  
                                    record_prefix="weather_", errors='ignore')
    weather_norm['station_id'] = station

    weather_df_capstone = pd.concat([weather_df_capstone, weather_norm], ignore_index=True)
weather_df_capstone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236808 entries, 0 to 236807
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   weather_date  236808 non-null  object
 1   weather_tavg  192253 non-null  object
 2   weather_tmin  202295 non-null  float64
 3   weather_tmax  202332 non-null  float64
 4   weather_prcp  180917 non-null  object
 5   weather_snow  131473 non-null  object
 6   weather_wdir  45645 non-null   object
 7   weather_wspd  190859 non-null  object
 8   weather_wpgt  7252 non-null    object
 9   weather_pres  175654 non-null  object
 10  weather_tsun  72590 non-null   object
 11  station_id    236808 non-null  object
dtypes: float64(2), object(10)
memory usage: 21.7+ MB

In [6]:
weather_df_capstone['weather_station_name'] = weather_df_capstone['station_id'].map(weather_stations_dict)

In [7]:
weather_df_capstone.head(10)

,weather_date,weather_tavg,weather_tmin,weather_tmax,weather_prcp,weather_snow,weather_wdir,weather_wspd,weather_wpgt,weather_pres,weather_tsun,station_id,weather_station_name
0,1996-01-01,9.4,7.7,10.5,NaN,NaN,NaN,6.9,NaN,NaN,NaN,KBFI0,Seattle / South Park
1,1996-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KBFI0,Seattle / South Park
2,1996-01-03,9.1,7.2,10.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KBFI0,Seattle / South Park
3,1996-01-04,6.0,3.8,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KBFI0,Seattle / South Park
4,1996-01-05,4.5,3.8,6.6,NaN,NaN,NaN,7.9,NaN,NaN,NaN,KBFI0,Seattle / South Park
5,1996-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KBFI0,Seattle / South Park
6,1996-01-07,11.1,8.8,13.8,NaN,NaN,NaN,13.5,NaN,NaN,NaN,KBFI0,Seattle / South Park
7,1996-01-08,9.1,6.6,13.3,NaN,NaN,NaN,9.1,NaN,NaN,NaN,KBFI0,Seattle / South Park
8,1996-01-09,8.1,4.4,11.1,NaN,NaN,NaN,12.7,NaN,NaN,NaN,KBFI0,Seattle / South Park
9,1996-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KBFI0,Seattle / South Park

In [1]:
# Import get_engine function from sql_functions.py and set it to a variable called engine
from sql_functions import get_engine 
engine = get_engine()
# Import psycopg2
import psycopg2

In [2]:
schema = 'capstone_wildfire' # example 'hh_analytics_22_1
table_name_1 = 'weather_1996-2005' # gives the table name in SQL

In [3]:
# Write records stored in a dataframe to SQL database
if engine!=None:
    try:
        weather_df_capstone.to_sql(table_name_1, # Name of SQL table
                        con=engine, # Engine or connection
                        if_exists='replace', # Drop the table before inserting new values 
                        schema=schema, # your class schema
                        index=False, # Write DataFrame index as a column
                        chunksize=5000, # Specify the number of rows in each batch to be written at a time
                        method='multi') # Pass multiple values in a single INSERT clause
        print(f"The {table_name_1} table was imported successfully.")
    # Error handling
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        engine = None

name 'weather_df_capstone' is not defined